language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
branches:
  only:
    - master
    - tvars
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
